import tkinter as tk
from tkinter import messagebox
from gui.lib import export_mcfunction, global_storage
from gui.selection.select_traj import TrajectorySelect

datapack_name = ''
datapack_namespace = ''
datapack_description = ''
output_dir = ''


class DatapackForm:
    # 1st page
    def __init__(self, root):
        self.root = root
        self.root.title("Datapack Generator")
        tk.Label(self.root, text="Datapack Generator", font=('Arial', 50, 'bold')).grid(
            row=0,
            column=0,
            pady=50,
            padx=50,
            columnspan=3)
        datapack_entries_frame = tk.LabelFrame(self.root, text='Datapack info')
        datapack_entries_frame.grid(column=0, row=1, padx=30, sticky=tk.NSEW)
        self.entries = {}
        labels = ['Datapack name', '(*) Datapack namespace', 'Datapack description']
        insertions = ['DynFirework', 'firework', 'fireworks generated by DynFirework']
        for i, label in enumerate(labels):
            tk.Label(datapack_entries_frame, text=label).grid(row=i + 1, column=0, padx=30, pady=20, sticky=tk.E)
            entry = tk.Entry(datapack_entries_frame, width=30)
            entry.insert(0, insertions[i])
            entry.grid(row=i + 1, column=1, padx=30, pady=20)
            self.entries[label] = entry
        tk.Button(self.root, text="Submit", command=lambda: self.submit()).grid(
            row=4,
            column=0,
            pady=30,
            columnspan=2)

    def submit(self):
        submits = {key: entry.get() for key, entry in self.entries.items()}
        global datapack_name
        global datapack_namespace
        global datapack_description
        global output_dir
        datapack_name = submits["Datapack name"]
        datapack_namespace = submits["(*) Datapack namespace"]
        datapack_description = submits["Datapack description"]
        output_dir = global_storage.project_dir + f"/{datapack_name}/data/{datapack_namespace}/functions/"
        messagebox.showinfo(
            'Datapack Generator',
            f'Created minecraft 1.16.5 datapack\ndatapack name:{datapack_name}\ndatapack namespace:{datapack_namespace}\ndatapack description:\n{datapack_description}')
        export_mcfunction.generate_data_pack(datapack_name, datapack_namespace, datapack_description)
        for widget in self.root.winfo_children():
            widget.destroy()
        TrajectorySelect(self.root)
