# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/thf/Repositories/qt-study/tests/df_about.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
	def setupUi(self, Dialog):
		Dialog.setObjectName("Dialog")
		Dialog.resize(339, 206)
		self.gridLayout = QtWidgets.QGridLayout(Dialog)
		self.gridLayout.setObjectName("gridLayout")
		self.label = QtWidgets.QLabel(Dialog)
		font = QtGui.QFont()
		font.setFamily("JetBrainsMonoNL Nerd Font Mono")
		font.setBold(True)
		font.setWeight(75)
		self.label.setFont(font)
		self.label.setTextFormat(QtCore.Qt.MarkdownText)
		self.label.setAlignment(QtCore.Qt.AlignCenter)
		self.label.setObjectName("label")
		self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
		self.label_2 = QtWidgets.QLabel(Dialog)
		font = QtGui.QFont()
		font.setFamily("Noto Sans")
		font.setItalic(True)
		self.label_2.setFont(font)
		self.label_2.setTextFormat(QtCore.Qt.MarkdownText)
		self.label_2.setAlignment(QtCore.Qt.AlignCenter)
		self.label_2.setObjectName("label_2")
		self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
		self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
		self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
		self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
		self.buttonBox.setObjectName("buttonBox")
		self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 1)
		self.label_3 = QtWidgets.QLabel(Dialog)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
		self.label_3.setSizePolicy(sizePolicy)
		self.label_3.setTextFormat(QtCore.Qt.MarkdownText)
		self.label_3.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
		self.label_3.setObjectName("label_3")
		self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)

		self.retranslateUi(Dialog)
		self.buttonBox.accepted.connect(Dialog.accept)  # type: ignore
		self.buttonBox.rejected.connect(Dialog.reject)  # type: ignore
		QtCore.QMetaObject.connectSlotsByName(Dialog)

	def retranslateUi(self, Dialog):
		_translate = QtCore.QCoreApplication.translate
		Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
		self.label.setText(_translate("Dialog", "# DynFirework"))
		self.label_2.setText(_translate("Dialog", "*Powered By* **PyQt5**"))
		self.label_3.setText(_translate("Dialog", "Version: v1.3 snapshot\n"
		                                          "\n"
		                                          "Firework Templates Provider: TianKong-y\n"
		                                          "\n"
		                                          "GUI Provider: MCXCC303"))
